name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get short commit hash and commit message
        id: commit_info
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "::set-output name=hash::${COMMIT_HASH}"
          echo "::set-output name=message::${COMMIT_MESSAGE}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./RGIS_IvancicBencak/Dockerfile
          push: true
          tags: domenbencak/rgis:${{ steps.commit_info.outputs.hash }}-latest

      - name: Logout from Docker Hub
        run: docker logout
