name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Get short commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./RGIS_IvancicBencak/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rgis:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/rgis:${{ steps.commit_hash.outputs.hash }}

      - name: Logout from Docker Hub
        run: docker logout
